In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()
data = pd.read_csv('country.csv')
data.head()

Saving country.csv to country.csv

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

data = pd.read_csv('country.csv')
data

##  Country.csv dosyasının özelliği
Bu tablo, çeşitli ülkelerle ilgili bir dizi demografik, ekonomik ve coğrafi veriyi içermektedir. Tabloda her bir satır bir ülkeyi temsil ederken, sütunlar bu ülkelerle ilgili farklı özellikleri gösterir. İşte sütunların anlamları:

Country: Ülkenin adı.  
Region: Ülkenin bulunduğu bölge (örneğin, Asya, Doğu Avrupa).  
Population: Ülkenin toplam nüfusu.  
Area (sq. mi.): Ülkenin yüzölçümü (mil kare olarak).  
Pop. Density (per sq. mi.): Nüfus yoğunluğu (mil kare başına düşen kişi sayısı).  
Coastline (coast/area ratio): Sahil uzunluğunun, ülkenin toplam alanına oranı.  
Net migration: Net göç oranı (göçmenlerin ülkeye giren veya ülkeden çıkan kişi sayısına göre oranı).  
Infant mortality (per 1000 births): Bebek ölüm oranı (1000 doğum başına).  
GDP ($ per capita): Kişi başına düşen Gayri Safi Yurtiçi Hasıla (GSYİH).  
Literacy (%): Okur-yazarlık oranı.  
Phones (per 1000): Her 1000 kişi başına düşen telefon sayısı.  
Arable (%): Tarıma elverişli arazi yüzdesi.  
Crops (%): Ekilebilir ürünlerin yüzdesi.  
Other (%): Diğer arazi kullanımı yüzdesi.  
Climate: Ülkenin iklim kategorisi (numerik bir değer olarak gösterilmiş).  
Birthrate: Doğum oranı.  
Deathrate: Ölüm oranı.  
Agriculture: Tarım sektörünün ekonomideki payı.  
Industry: Sanayi sektörünün ekonomideki payı.  
Service: Hizmet sektörünün ekonomideki payı.

## Bu Dosyada Yapacağınız görevleri alt taraftan bakabilirsiniz.

## 1. Görev : Nüfusa Göre Azalan Sırada Sıralama:

In [ ]:
# Nüfusa Göre Azalan Sırada Sıralama kodunu buraya yazınız
data.Population.sort_values()

174          7026
171          7502
140          9439
209         11810
144         13287
          ...
27      188078227
95      245452739
214     298444215
94     1095351995
42     1313973713
Name: Population, Length: 227, dtype: int64

## 2. Görev: GDP per capita sütununa göre ülkeleri artan sırada sıralamak(Kişi başına düşen Gayri Safi Yurtiçi Hasıla).

In [ ]:
# GDP per capita sütununa göre ülkeleri artan sırada sıralamak(Kişi başına düşen Gayri Safi Yurtiçi Hasıla). kodunu buradan yazınız.
siralanmis=data.sort_values(by="GDP ($ per capita)",ascending=False)
print(siralanmis[["Country","GDP ($ per capita)"]])

             Country  GDP ($ per capita)
121      Luxembourg              55100.0
154          Norway              37800.0
214   United States              37800.0
22          Bermuda              36000.0
38   Cayman Islands              35000.0
..               ...                 ...
125          Malawi                600.0
183    Sierra Leone                500.0
188         Somalia                500.0
58       East Timor                500.0
223  Western Sahara                  NaN

[227 rows x 2 columns]

## 1. Görev : Nüfusa Göre Azalan Sırada Sıralama:

In [ ]:
# Nüfusa Göre Azalan Sırada Sıralama kodunu buraya yazınız

data.Population.sort_values()

174          7026
171          7502
140          9439
209         11810
144         13287
          ...
27      188078227
95      245452739
214     298444215
94     1095351995
42     1313973713
Name: Population, Length: 227, dtype: int64

## 3. Görev: Population sütunu 10 milyonun üzerinde olan ülkeleri seçmek.

In [ ]:
# Kodunu buraya yazınız.

data1=data[data['Population'] > 10000000]

print(data1[["Country","Population"]])

          Country  Population
0    Afghanistan     31056997
2        Algeria     32930091
5         Angola     12127071
8      Argentina     39921833
11     Australia     20264082
..            ...         ...
218    Venezuela     25730435
219      Vietnam     84402966
224        Yemen     21456188
225       Zambia     11502010
226     Zimbabwe     12236805

[79 rows x 2 columns]

## 4. Görev: Literacy (%) sütununa göre ülkeleri sıralayıp, en yüksek okur-yazarlık oranına sahip ilk 5 ülkeyi seçmek.

In [ ]:
# Kodunu buraya yazınız.
siralanmis=data.sort_values(by="Literacy (%)",ascending=False).head(5)
print(siralanmis[["Country","GDP ($ per capita)"]])

             Country  GDP ($ per capita)
53   Czech Republic              15700.0
93          Iceland              30900.0
163          Poland              11100.0
114          Latvia              10200.0
64          Estonia              12300.0

## 5. Görev:  Kişi Başı GSYİH 10.000'in Üzerinde Olan Ülkeleri Filtreleme: GDP ( per capita) sütunu 10.000'in üzerinde olan ülkeleri seçmek.

In [ ]:
# Kodunu buraya yazınız.

data1=data[data['GDP ($ per capita)'] > 10000]

print(data1[["Country","GDP ($ per capita)"]])

                   Country  GDP ($ per capita)
4                 Andorra              19000.0
7       Antigua & Barbuda              11000.0
8               Argentina              11200.0
10                  Aruba              28000.0
11              Australia              29000.0
..                     ...                 ...
212  United Arab Emirates              23200.0
213        United Kingdom              27700.0
214         United States              37800.0
215               Uruguay              12800.0
220        Virgin Islands              17200.0

[76 rows x 2 columns]

## Görev 6 : En Yüksek Nüfus Yoğunluğuna Sahip İlk 10 Ülkeyi Seçme:
Pop. Density (per sq. mi.) sütununa göre ülkeleri sıralayıp, en yüksek nüfus yoğunluğuna sahip ilk 10 ülkeyi seçmek.

In [ ]:
# Kodunu buraya yazınız.
siralanmis=data.sort_values(by="Pop. Density (per sq. mi.)",ascending=False).head(10)
print(siralanmis[["Country","Pop. Density (per sq. mi.)"]])

         Country Pop. Density (per sq. mi.)
9       Armenia                        99,9
186    Slovenia                        99,2
202        Togo                        97,7
12      Austria                        97,7
168     Romania                        93,9
77        Ghana                        93,6
140  Montserrat                        92,5
13   Azerbaijan                        91,9
56     Dominica                        91,4
206      Turkey                        90,2